openapi: 3.0.1
info:
  title: '@jupiterone/graph-rapid7-insight'
  description: A graph conversion tool for Rapid7 Insight Platform
  x-cortex-git:
    github:
      repository: JupiterOne/graph-rapid7-insight
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-rapid7-insight'
